spring:
  jackson:
    time-zone: 'Asia/Seoul'
  #multipart upload?? ????
  #default : 1MB
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/large_board
    username: root
    password: 1234

  jpa:
    # ?????? ???? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # JPA Open EntityManager in View ??? ??? ?? ????
    open-in-view: false
    # JPA ?? ?? ???? SQL? ??? ??? ?????.
    show-sql: true
    hibernate:
      # ????? validate? none?? ?????.
      # ???? ??? ?????.
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        # ?? JPA? ???? Hibernate ? ????? ???? SQL? ????? ?????.
        # ???? SQL? ???? ?? ???.
        format_sql: true
        # LAZY ?? ? ????? ???? ?? ??? ??
        # fetch join ??? ???
        default_batch_fetch_size: 100
        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
    redis:
      host: redis
      port: 6379
      password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  rabbitmq:
#    host: rabbitmq
#    username: guest
#    password: guest
#    port: 5672

jwt:
  secret_key: dsaoiuxcjxzkjckxjcsakjksaeyhadkmcxnnbcmnvbcxnmvbcxnmvxuehfsdklfjdslk
  access:
    expiration: 3600
  refresh:
    expiration: 864000000

logging:
  level:
    org.springframework.cache: trace # Redis ??? ?? ??? ????? ??
    com:
      example:
        board: DEBUG
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
      # Hibernate ?????? ?? org.hibernate.SQL ???? ????? ?? ?? ??? ?????.
      # ?? ?????? ???? ?? ?? ??? ?? ????? ? ? ?????.
      # Hibernate? SQL ??? ??? ?? ?? ? ?????.
      hibernate:
        SQL: debug
    # ? ??? ?????? ???? ?? ??? ?????.
    # root? ??? ?? ???? ?????.
    # ??? root ??? ??? ?? ????? ?? ?? ??? debug? ?????.
    # ?? ?????? ??? ???? ???? ??? ??? ??? ?? ??? ? ????.
    root: info




